### ISSUE TITLE
first feedback, code structure & another stuffs

### ISSUE THREAD

**Issue by Taalaybek** [wpseed/inertia-laravel-crud-generator#1]

**Comment by Taalaybek** [comment]
My opinion generate vue views with code is overhead
I suppose leave them empty

**Comment by Taalaybek** [comment]
Maybe camelcase will be better? And will be better if we remove laravel from name, we are already in laravel environment ))
[Facade](https://github.com/wpseed/inertia-laravel-crud-generator/blob/a66191495db7c24f8a07fb76c1545b2cf7e22eb7/src/Facades/InertiaLaravelCrudGenerator.php)

**Comment by zorca** [comment]
> 
> 
> My opinion generate vue views with code is overhead
> I suppose leave them empty

Thank you for your feedback. I will make options for generating different stub options. We need the completed code in the views to generate it in our production company, for which the package is being created. I will make an option for more simplest generation by default.
